"use client";
import { useEffect, useRef, useState } from "react";
import { RotateCcw, ArrowUpRight, Users, Sparkles } from "lucide-react";
import { Back } from "@/components/games/shell";
import { flushSync } from "react-dom";

type Mark = "X" | "O";
type Game = { board: (Mark|null)[]; turn: Mark; starter: Mark; round: number; scores: {X:number;O:number;draw:number} };
const lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function outcome(board: Game["board"]) { const line=lines.find(l=>board[l[0]] && l.every(i=>board[i]===board[l[0]])); return {winner:line ? board[line[0]]:null,line:line??[],draw:!line && board.every(Boolean)}; }
const initial:Game={board:Array(9).fill(null),turn:"X",starter:"X",round:1,scores:{X:0,O:0,draw:0}};
export default function Home(){
 const [ready,setReady]=useState(false); useEffect(()=>setReady(true),[]);
 const [game,setGame]=useState<Game>(initial); const ref=useRef(game); ref.current=game;
 const result=outcome(game.board); const ended=!!result.winner||result.draw;
 function play(index:number){const g=ref.current;if(!Number.isInteger(index)||index<0||index>8)throw new Error("Choose a cell from 1 to 9.");if(outcome(g.board).winner||outcome(g.board).draw)throw new Error("This round has finished.");if(g.board[index])throw new Error("This cell is occupied.");const board=[...g.board];board[index]=g.turn;const r=outcome(board);const scores={...g.scores};if(r.winner)scores[r.winner]++;else if(r.draw)scores.draw++;const next={...g,board,scores,turn:g.turn==="X"?"O" as const:"X" as const};ref.current=next;setGame(next);return next;}
 function restart(){const g=ref.current;const finished=outcome(g.board);const starter=finished.winner||finished.draw?(g.starter==="X"?"O":"X"):g.starter;const next:Game={...g,board:Array(9).fill(null),turn:starter,starter,round:g.round+(finished.winner||finished.draw?1:0)};ref.current=next;setGame(next);return next;}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();for(const tool of [{name:"read_game",description:"Read the board, turn, round and scores.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...ref.current,...outcome(ref.current.board)})},{name:"play_cell",description:"Place the current player's mark in an empty cell numbered 1 to 9, from top left to bottom right.",inputSchema:{type:"object",properties:{cell:{type:"integer",minimum:1,maximum:9}},required:["cell"],additionalProperties:false},execute:(input:any)=>{let state;flushSync(()=>{state=play(input.cell-1)});return state;}},{name:"restart_round",description:"Clear the current round, or start the next round after a result. Keeps scores.",inputSchema:{type:"object",properties:{},additionalProperties:false},execute:()=>{let state;flushSync(()=>{state=restart()});return state;}}]){try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[]);
 return <div className="app-shell">
 <header className="topbar"><a href="/" className="brand" aria-label="Three in a Row home"><span className="brand-symbol">#</span> playground<span className="brand-period">.</span></a><span className="mode"><Users size={15}/> TWO PLAYERS · ONE SCREEN</span></header>
 <main><Back/><div className="intro game-intro"><div className="eyebrow"><span/> THE CLASSICS NEVER GET OLD</div><h1>Three in a <span>row.</span></h1><p>A little strategy. A little rivalry. Your move.</p></div>
 <section className="arena" aria-label="Tic-Tac-Toe game">
 <aside className={`player-card x-card ${!ended&&game.turn==='X'?'active':''}`}><div className="card-top"><span>PLAYER 01</span><span className="player-state">{result.winner==='X'?'WINNER':!ended&&game.turn==='X'?'YOUR TURN':'X'}</span></div><div className="large-mark">×</div><h2>Team Cross</h2><p>Make your mark.</p><div className="score"><strong>{String(game.scores.X).padStart(2,'0')}</strong><span>ROUNDS WON</span></div></aside>
 <div className="play-area"><div className="round-line"><span>ROUND {String(game.round).padStart(2,'0')}</span><span>PASS & PLAY</span></div><div className={`board ${ended?'finished':''}`} role="group" aria-label="Game board">{game.board.map((mark,i)=><button key={i} className={`cell ${mark?.toLowerCase()??''} ${result.line.includes(i)?'winning':''}`} disabled={!ready||!!mark||ended} onClick={()=>play(i)} aria-label={`Row ${Math.floor(i/3)+1}, column ${i%3+1}: ${mark??'empty'}`}><span>{mark==='X'?'×':mark==='O'?'○':''}</span>{!mark&&!ended&&<span className={`ghost ${game.turn.toLowerCase()}`}>{game.turn==='X'?'×':'○'}</span>}</button>)}</div><div className="game-status" role="status" aria-live="polite"><span className={`status-mark ${result.winner?.toLowerCase()??game.turn.toLowerCase()}`}>{result.draw?'=':(result.winner??game.turn)==='X'?'×':'○'}</span><div><strong>{result.winner?`Team ${result.winner==='X'?'Cross':'Circle'} wins!`:result.draw?"A worthy match. It's a draw!":`Team ${game.turn==='X'?'Cross':'Circle'}'s turn`}</strong><p>{ended?'Ready for a rematch?':'Pick an empty square to play.'}</p></div>{result.winner&&<Sparkles size={22} className="sparkle"/>}</div><button className="restart" disabled={!ready} onClick={restart}>{ended?<ArrowUpRight size={18}/>:<RotateCcw size={16}/>} {ended?'Play next round':'Restart round'}</button></div>
 <aside className={`player-card o-card ${!ended&&game.turn==='O'?'active':''}`}><div className="card-top"><span>PLAYER 02</span><span className="player-state">{result.winner==='O'?'WINNER':!ended&&game.turn==='O'?'YOUR TURN':'O'}</span></div><div className="large-mark">○</div><h2>Team Circle</h2><p>Come full circle.</p><div className="score"><strong>{String(game.scores.O).padStart(2,'0')}</strong><span>ROUNDS WON</span></div></aside>
 </section>
 <div className="match-meta"><span><span className="draw-count">{game.scores.draw}</span> {game.scores.draw===1?'draw':'draws'} this session</span><span className="divider"/><span>First move alternates each round</span></div>
 <section className="rules" aria-label="How to play"><h2>Small board.<br/>Big possibilities.</h2><div><span className="rule-number">01</span><p><strong>Take turns</strong>Place your X or O in an empty square.</p></div><div><span className="rule-number">02</span><p><strong>Connect three</strong>Line up three across, down, or diagonally.</p></div><div><span className="rule-number">03</span><p><strong>Run it back</strong>Full board? Call it a draw and play again.</p></div></section>
 </main><footer><span>BUILT FOR A LITTLE FRIENDLY COMPETITION</span><span>Good games. Better company.</span></footer></div>
}
