"use client";
import { useEffect, useRef, useState } from 'react';
import { Circle, Hand, Scissors, LockKeyhole, ArrowUpRight, RotateCcw } from 'lucide-react';
import { Header, Back, Footer } from '@/components/games/shell';
import { choices, rpsWinner, type Choice } from '@/lib/game-logic';
const Icons={rock:Circle,paper:Hand,scissors:Scissors};
type Phase='first'|'handoff'|'second'|'ready'|'result';
export default function RockPaperScissors(){
 const [ready,setReady]=useState(false); useEffect(()=>setReady(true),[]);
 const [game,setGame]=useState({phase:'first' as Phase,first:null as Choice|null,second:null as Choice|null,round:1,scores:[0,0,0]});const ref=useRef(game);ref.current=game;
 function update(next:typeof game){ref.current=next;setGame(next);}
 function choose(choice:Choice){const g=ref.current;if(g.phase==='first')update({...g,first:choice,phase:'handoff'});else if(g.phase==='second')update({...g,second:choice,phase:'ready'});}
 function proceed(){const g=ref.current;if(g.phase==='handoff')update({...g,phase:'second'});else if(g.phase==='ready'&&g.first&&g.second){const scores=[...g.scores];scores[rpsWinner(g.first,g.second)]++;update({...g,scores,phase:'result'});}}
 function restart(){const g=ref.current;update({...g,phase:'first',first:null,second:null,round:g.round+(g.phase==='result'?1:0)});}
 const choosing=game.phase==='first'||game.phase==='second',done=game.phase==='result';const winner=done&&game.first&&game.second?rpsWinner(game.first,game.second):null;
 return <div className="app-shell"><Header/><main><Back/><div className="intro game-intro"><div className="eyebrow"><span/> TRUST YOUR INSTINCT</div><h1 className="rps-heading">Rock. Paper. <span>Scissors.</span></h1><p>Make your choice. Keep them guessing.</p></div><section className="rps-game"><div className="compact-score"><div className="player-one"><span className="disc-token"/><div><strong>Player 1</strong><span>{game.first&&!done?'LOCKED IN':'ROUNDS WON'}</span></div><b>{game.scores[1]}</b></div><span className="versus">VS</span><div className="player-two"><span className="disc-token"/><div><strong>Player 2</strong><span>{game.second&&!done?'LOCKED IN':'ROUNDS WON'}</span></div><b>{game.scores[2]}</b></div></div><div className="round-line"><span>ROUND {String(game.round).padStart(2,'0')}</span><span>{game.scores[0]} DRAWS</span></div><div className="rps-stage"><div role="status" aria-live="polite" aria-atomic="true"><h2>{choosing?`Player ${game.phase==='first'?1:2}, choose your move.`:game.phase==='handoff'?'Your move is locked.':game.phase==='ready'?'Two choices. One reveal.':winner===0?"Great minds think alike.":`Player ${winner} wins!`}</h2><p>{choosing?'Other player: look away while the choice is made.':game.phase==='handoff'?'Pass the device to Player 2. Your choice stays hidden.':game.phase==='ready'?'Bring both players back to the screen.':winner===0?"It's a draw. Go again?":`${(winner===1?game.first:game.second)} beats ${(winner===1?game.second:game.first)}.`}</p></div>
 {choosing?<div className="choice-grid">{choices.map(choice=>{const Icon=Icons[choice];return <button key={game.phase+choice} className="choice-button" disabled={!ready} onClick={()=>choose(choice)}><Icon size={46}/><strong>{choice}</strong></button>})}</div>:done?<div className="reveal-grid">{[game.first,game.second].map((choice,i)=>{const Icon=Icons[choice!];return <div className={`reveal-card ${winner===i+1?'reveal-winner':''}`} key={i}><span>PLAYER {i+1}</span><Icon size={58}/><strong>{choice}</strong><small>{winner===0?'DRAW':winner===i+1?'WINNER':'NEXT TIME'}</small></div>})}</div>:<div className="handoff"><span className="lock-icon"><LockKeyhole size={40}/></span><button className="primary-action" onClick={proceed}>{game.phase==='handoff'?"I'm Player 2 — ready":"Reveal our choices"}<ArrowUpRight size={18}/></button></div>}
 </div><button className="restart" disabled={!ready} onClick={restart}>{done?<ArrowUpRight size={18}/>:<RotateCcw size={16}/>} {done?'Play next round':'Restart round'}</button><p className="game-footnote">Choices stay hidden until the reveal · Scores last until you leave this game</p></section><section className="simple-rules"><strong>The winning triangle</strong><p>Rock beats scissors. Scissors beat paper. Paper beats rock. Matching choices are a draw. Player 1 chooses first, passes the device, then Player 2 chooses. Reveal only when both players are ready.</p></section></main><Footer/></div>
}
