"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, RotateCcw } from 'lucide-react';
import { Header, Back, Footer } from '@/components/games/shell';
import { connectResult, dropDisc, type Disc, type Player } from '@/lib/game-logic';
export default function ConnectFour(){
 const [ready,setReady]=useState(false); useEffect(()=>setReady(true),[]);
 const [game,setGame]=useState({board:Array(42).fill(null) as Disc[],turn:1 as Player,starter:1 as Player,round:1,scores:[0,0,0]});const ref=useRef(game);ref.current=game;
 const result=connectResult(game.board), ended=!!result.winner||result.draw;
 function drop(col:number){const g=ref.current;const old=connectResult(g.board);if(old.winner||old.draw||g.board[col])return;const board=dropDisc(g.board,col,g.turn),r=connectResult(board),scores=[...g.scores];if(r.winner)scores[r.winner]++;else if(r.draw)scores[0]++;const next={...g,board,scores,turn:(g.turn===1?2:1) as Player};ref.current=next;setGame(next);}
 function restart(){const g=ref.current,r=connectResult(g.board),over=!!r.winner||r.draw;const starter=(over?(g.starter===1?2:1):g.starter) as Player;const next={...g,board:Array(42).fill(null),turn:starter,starter,round:g.round+(over?1:0)};ref.current=next;setGame(next);}
 return <div className="app-shell"><Header/><main><Back/><div className="intro game-intro"><div className="eyebrow"><span/> ONE STEP AHEAD</div><h1>Connect <span>four.</span></h1><p>Drop a disc. Find your line.</p></div><section className="connect-layout"><div className="compact-score"><div className={game.turn===1&&!ended?'on player-one':'player-one'}><span className="disc-token"/><div><strong>Player 1</strong><span>LIME</span></div><b>{game.scores[1]}</b></div><span className="versus">VS</span><div className={game.turn===2&&!ended?'on player-two':'player-two'}><span className="disc-token"/><div><strong>Player 2</strong><span>VIOLET</span></div><b>{game.scores[2]}</b></div></div><div className="round-line"><span>ROUND {String(game.round).padStart(2,'0')}</span><span>{game.scores[0]} DRAWS</span></div><div className={`connect-board turn-${game.turn}`}><div className="column-controls">{Array.from({length:7},(_,col)=><button key={col} onClick={()=>drop(col)} disabled={!ready||ended||!!game.board[col]} aria-label={`Drop disc in column ${col+1}${game.board[col]?', full':''}`}><ArrowDown size={20}/><span>{col+1}</span></button>)}</div><div className="disc-grid" role="group" aria-label="Connect Four board, rows from top to bottom">{game.board.map((disc,i)=><div key={i} className={`disc-hole ${disc?'disc-'+disc:''} ${result.line.includes(i)?'connected':''}`} aria-label={`Row ${Math.floor(i/7)+1}, column ${i%7+1}: ${disc?'Player '+disc:'empty'}`}><span>{disc===1?'•':disc===2?'◦':''}</span></div>)}</div></div><div className="game-status" role="status" aria-live="polite"><span className={`status-disc disc-${result.winner??game.turn}`}/><div><strong>{result.winner?`Player ${result.winner} wins!`:result.draw?'The board is full. A draw!':`Player ${game.turn}'s turn`}</strong><p>{ended?'Ready for another round?':'Choose a column using the arrows above.'}</p></div></div><button className="restart" disabled={!ready} onClick={restart}>{ended?<ArrowUpRight size={18}/>:<RotateCcw size={16}/>} {ended?'Play next round':'Restart round'}</button><p className="game-footnote">First move alternates each round · Scores last until you leave this game</p></section><section className="simple-rules"><strong>How to play</strong><p>Players take turns dropping a disc into one of seven columns. Discs fall to the lowest empty space. Connect four of your discs horizontally, vertically, or diagonally to win. A full board without a winner is a draw.</p></section></main><Footer/></div>
}
